// <auto-generated />
using System;
using ArcanoPizza_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcanoPizza_API.Data.Migrations
{
    [DbContext(typeof(ArcanoPizzaDbContext))]
    partial class ArcanoPizzaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArcanoPizza_API.Model.CategoriaProducto", b =>
                {
                    b.Property<int>("IdCategoriasProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoriasProductos"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCategoriasProductos");

                    b.ToTable("categorias_producto", (string)null);
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccion"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDireccion");

                    b.HasIndex("FkIdUsuario");

                    b.ToTable("direcciones", (string)null);
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Extra", b =>
                {
                    b.Property<int>("IdExtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExtra"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdExtra");

                    b.ToTable("extras", (string)null);
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FkIdPedido")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProveedorPagoId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPago");

                    b.HasIndex("FkIdPedido")
                        .IsUnique();

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FkIdDireccion")
                        .HasColumnType("int");

                    b.Property<int>("FkIdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Impuestos")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("TipoEntrega")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPedido");

                    b.HasIndex("FkIdDireccion");

                    b.HasIndex("FkIdUsuario");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.PedidoItem", b =>
                {
                    b.Property<int>("IdPedidoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedidoItem"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("FkIdPedido")
                        .HasColumnType("int");

                    b.Property<int>("FkIdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("FkIdTamanoPizza")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPedidoItem");

                    b.HasIndex("FkIdPedido");

                    b.HasIndex("FkIdProducto");

                    b.HasIndex("FkIdTamanoPizza");

                    b.ToTable("pedidos_item", (string)null);
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.PedidoItemExtra", b =>
                {
                    b.Property<int>("IdPedidoItemExtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedidoItemExtra"));

                    b.Property<int>("FkIdExtra")
                        .HasColumnType("int");

                    b.Property<int>("FkIdPedidoItem")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioExtra")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPedidoItemExtra");

                    b.HasIndex("FkIdExtra");

                    b.HasIndex("FkIdPedidoItem");

                    b.ToTable("pedidos_item_extras", (string)null);
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FkIdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdProducto");

                    b.HasIndex("FkIdCategoria");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.TamanoPizza", b =>
                {
                    b.Property<int>("IdPizza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPizza"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ModificadorPrecio")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPizza");

                    b.ToTable("tamanos_pizza", (string)null);
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUsuario");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Direccion", b =>
                {
                    b.HasOne("ArcanoPizza_API.Model.Usuario", "Usuario")
                        .WithMany("Direcciones")
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Pago", b =>
                {
                    b.HasOne("ArcanoPizza_API.Model.Pedido", "Pedido")
                        .WithOne("Pago")
                        .HasForeignKey("ArcanoPizza_API.Model.Pago", "FkIdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Pedido", b =>
                {
                    b.HasOne("ArcanoPizza_API.Model.Direccion", "Direccion")
                        .WithMany("Pedidos")
                        .HasForeignKey("FkIdDireccion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcanoPizza_API.Model.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("FkIdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Direccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.PedidoItem", b =>
                {
                    b.HasOne("ArcanoPizza_API.Model.Pedido", "Pedido")
                        .WithMany("PedidosItem")
                        .HasForeignKey("FkIdPedido")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcanoPizza_API.Model.Producto", "Producto")
                        .WithMany("PedidosItem")
                        .HasForeignKey("FkIdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcanoPizza_API.Model.TamanoPizza", "TamanoPizza")
                        .WithMany("PedidosItem")
                        .HasForeignKey("FkIdTamanoPizza")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pedido");

                    b.Navigation("Producto");

                    b.Navigation("TamanoPizza");
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.PedidoItemExtra", b =>
                {
                    b.HasOne("ArcanoPizza_API.Model.Extra", "Extra")
                        .WithMany("PedidosItemExtras")
                        .HasForeignKey("FkIdExtra")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ArcanoPizza_API.Model.PedidoItem", "PedidoItem")
                        .WithMany("PedidosItemExtras")
                        .HasForeignKey("FkIdPedidoItem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Extra");

                    b.Navigation("PedidoItem");
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Producto", b =>
                {
                    b.HasOne("ArcanoPizza_API.Model.CategoriaProducto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("FkIdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Direccion", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Extra", b =>
                {
                    b.Navigation("PedidosItemExtras");
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Pedido", b =>
                {
                    b.Navigation("Pago");

                    b.Navigation("PedidosItem");
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.PedidoItem", b =>
                {
                    b.Navigation("PedidosItemExtras");
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Producto", b =>
                {
                    b.Navigation("PedidosItem");
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.TamanoPizza", b =>
                {
                    b.Navigation("PedidosItem");
                });

            modelBuilder.Entity("ArcanoPizza_API.Model.Usuario", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
